/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  das_edit: () => import("@/views/das/edit/index.vue"),
  das_favorite: () => import("@/views/das/favorite/index.vue"),
  das_history: () => import("@/views/das/history/index.vue"),
  das: () => import("@/views/das/index.vue"),
  "das_orders-detail": () => import("@/views/das/orders-detail/index.vue"),
  "das_orders-list": () => import("@/views/das/orders-list/index.vue"),
  das_orders_commit: () => import("@/views/das/orders/commit/index.vue"),
  das_orders_ddl: () => import("@/views/das/orders/ddl/index.vue"),
  das_orders_dml: () => import("@/views/das/orders/dml/index.vue"),
  das_orders_export: () => import("@/views/das/orders/export/index.vue"),
  home: () => import("@/views/home/index.vue"),
  system_database_config: () => import("@/views/system/database/config/index.vue"),
  system_database_environment: () => import("@/views/system/database/environment/index.vue"),
  system_database_inspect: () => import("@/views/system/database/inspect/index.vue"),
  system_database_permission: () => import("@/views/system/database/permission/index.vue"),
  system_database_permission_role: () => import("@/views/system/database/permission/role/index.vue"),
  system_database_permission_template: () => import("@/views/system/database/permission/template/index.vue"),
  system_database_permission_user: () => import("@/views/system/database/permission/user/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_permission: () => import("@/views/system/permission/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
