/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'das',
    path: '/das',
    component: 'layout.base',
    meta: {
      title: 'das',
      i18nKey: 'route.das',
      icon: 'mdi:database',
      order: 2
    },
    children: [
      {
        name: 'das_edit',
        path: '/das/edit',
        component: 'view.das_edit',
        meta: {
          title: 'das_edit',
          i18nKey: 'route.das_edit',
          icon: 'mdi:database-search'
        }
      },
      {
        name: 'das_favorite',
        path: '/das/favorite',
        component: 'view.das_favorite',
        meta: {
          title: 'das_favorite',
          i18nKey: 'route.das_favorite',
          hideInMenu: true
        }
      },
      {
        name: 'das_history',
        path: '/das/history',
        component: 'view.das_history',
        meta: {
          title: 'das_history',
          i18nKey: 'route.das_history',
          hideInMenu: true
        }
      },
      {
        name: 'das_orders',
        path: '/das/orders',
        meta: {
          title: 'das_orders',
          i18nKey: 'route.das_orders',
          icon: 'mdi:file-document-edit',
          order: 3
        },
        children: [
          {
            name: 'das_orders_commit',
            path: '/das/orders/commit',
            component: 'view.das_orders_commit',
            meta: {
              title: 'das_orders_commit',
              i18nKey: 'route.das_orders_commit',
              hideInMenu: true
            },
            children: [
              {
                name: 'das_orders_commit_export',
                path: '/das/orders/commit/export',
                component: 'view.das_orders_commit_export',
                meta: {
                  title: 'das_orders_commit_export',
                  i18nKey: 'route.das_orders_commit_export',
                  order: 3
                }
              }
            ]
          },
          {
            name: 'das_orders_ddl',
            path: '/das/orders/ddl',
            component: 'view.das_orders_ddl',
            meta: {
              title: 'das_orders_ddl',
              i18nKey: 'route.das_orders_ddl',
              icon: 'mdi:database-cog',
              order: 1
            }
          },
          {
            name: 'das_orders_dml',
            path: '/das/orders/dml',
            component: 'view.das_orders_dml',
            meta: {
              title: 'das_orders_dml',
              i18nKey: 'route.das_orders_dml',
              icon: 'mdi:database-edit',
              order: 2
            }
          },
          {
            name: 'das_orders_export',
            path: '/das/orders/export',
            component: 'view.das_orders_export',
            meta: {
              title: 'das_orders_export',
              i18nKey: 'route.das_orders_export',
              icon: 'mdi:database-export',
              order: 3
            }
          }
        ]
      },
      {
        name: 'das_orders-detail',
        path: '/das/orders-detail/:id',
        component: 'view.das_orders-detail',
        meta: {
          title: 'das_orders-detail',
          i18nKey: 'route.das_orders-detail',
          hideInMenu: true,
          activeMenu: 'das_orders-list'
        }
      },
      {
        name: 'das_orders-list',
        path: '/das/orders-list',
        component: 'view.das_orders-list',
        meta: {
          title: 'das_orders-list',
          i18nKey: 'route.das_orders-list',
          icon: 'mdi:format-list-bulleted',
          order: 2
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_database',
        path: '/system/database',
        component: 'layout.base',
        meta: {
          title: 'system_database',
          i18nKey: 'route.system_database',
          icon: 'mdi:database-cog',
          order: 1
        },
        children: [
          {
            name: 'system_database_config',
            path: '/system/database/config',
            component: 'view.system_database_config',
            meta: {
              title: 'system_database_config',
              i18nKey: 'route.system_database_config',
              icon: 'mdi:database-settings',
              order: 2
            }
          },
          {
            name: 'system_database_environment',
            path: '/system/database/environment',
            component: 'view.system_database_environment',
            meta: {
              title: 'system_database_environment',
              i18nKey: 'route.system_database_environment',
              icon: 'mdi:server-network',
              order: 1
            }
          },
          {
            name: 'system_database_inspect',
            path: '/system/database/inspect',
            component: 'view.system_database_inspect',
            meta: {
              title: 'system_database_inspect',
              i18nKey: 'route.system_database_inspect'
            }
          },
          {
            name: 'system_database_permission',
            path: '/system/database/permission',
            component: 'layout.base$view.system_database_permission',
            meta: {
              title: 'system_database_permission',
              i18nKey: 'route.system_database_permission',
              icon: 'mdi:shield-account',
              order: 3
            },
            children: [
              {
                name: 'system_database_permission_role',
                path: '/system/database/permission/role',
                component: 'view.system_database_permission_role',
                meta: {
                  title: 'system_database_permission_role',
                  i18nKey: 'route.system_database_permission_role'
                }
              },
              {
                name: 'system_database_permission_template',
                path: '/system/database/permission/template',
                component: 'view.system_database_permission_template',
                meta: {
                  title: 'system_database_permission_template',
                  i18nKey: 'route.system_database_permission_template'
                }
              },
              {
                name: 'system_database_permission_user',
                path: '/system/database/permission/user',
                component: 'view.system_database_permission_user',
                meta: {
                  title: 'system_database_permission_user',
                  i18nKey: 'route.system_database_permission_user'
                }
              }
            ]
          }
        ]
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_permission',
        path: '/system/permission',
        component: 'view.system_permission',
        meta: {
          title: 'system_permission',
          i18nKey: 'route.system_permission'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  }
];
